'use strict';

const crypto = require('node:crypto');

const TRANSITIONS = Object.freeze({
  planned: Object.freeze(['awaiting-approval', 'queued', 'cancelled', 'blocked']),
  'awaiting-approval': Object.freeze(['queued', 'cancelled', 'blocked']),
  queued: Object.freeze(['leased', 'cancelled', 'blocked']),
  leased: Object.freeze(['running', 'queued', 'cancelled', 'blocked']),
  running: Object.freeze(['waiting', 'retry-scheduled', 'paused', 'cancelling', 'verifying', 'failed', 'blocked']),
  waiting: Object.freeze(['queued', 'cancelled', 'blocked']),
  'retry-scheduled': Object.freeze(['queued', 'cancelled', 'blocked']),
  paused: Object.freeze(['queued', 'cancelled', 'blocked']),
  cancelling: Object.freeze(['cancelled', 'failed', 'blocked']),
  verifying: Object.freeze(['succeeded', 'failed', 'blocked']),
  succeeded: Object.freeze([]),
  failed: Object.freeze([]),
  cancelled: Object.freeze([]),
  blocked: Object.freeze([])
});
const TERMINAL = Object.freeze(['succeeded', 'failed', 'cancelled', 'blocked']);
const LEASE_HOLDING = Object.freeze(['leased', 'running', 'verifying', 'cancelling']);
const SECRET_FIELD = /(?:password|passwd|secret|credential|token|api[_-]?key|private[_-]?key|connection[_-]?string)/i;

function nonEmpty(value, label) {
  if (typeof value !== 'string' || !value.trim()) throw new TypeError(label + ' must be a nonempty string');
  return value;
}

function canonical(value, path = '$', seen = new Set()) {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (Array.isArray(value)) {
    if (seen.has(value)) throw new TypeError('cyclic job data at ' + path);
    seen.add(value);
    const output = value.map((item, index) => canonical(item, path + '[' + index + ']', seen));
    seen.delete(value);
    return output;
  }
  if (value && typeof value === 'object' && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null)) {
    if (seen.has(value)) throw new TypeError('cyclic job data at ' + path);
    seen.add(value);
    const output = Object.create(null);
    for (const key of Object.keys(value).sort()) {
      if (SECRET_FIELD.test(key)) throw new TypeError('secret-bearing job data field rejected at ' + path + '.' + key);
      if (['__proto__', 'constructor', 'prototype'].includes(key)) throw new TypeError('unsafe job data field at ' + path + '.' + key);
      output[key] = canonical(value[key], path + '.' + key, seen);
    }
    seen.delete(value);
    return output;
  }
  throw new TypeError('job data must contain only finite JSON values at ' + path);
}

function deepFreeze(value) {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(deepFreeze);
    Object.freeze(value);
  }
  return value;
}

function safeCopy(value) { return deepFreeze(canonical(value)); }

function createPlan(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new TypeError('job plan must be an object');
  const data = canonical(input);
  nonEmpty(data.jobKind, 'jobKind');
  nonEmpty(data.lifecyclePhase, 'lifecyclePhase');
  nonEmpty(data.targetIdentity, 'targetIdentity');
  if (!Array.isArray(data.steps) || data.steps.length === 0) throw new TypeError('job plan requires steps');
  const ids = new Set();
  for (const step of data.steps) {
    if (!step || Array.isArray(step) || typeof step !== 'object') throw new TypeError('job step must be an object');
    nonEmpty(step.stepId, 'stepId');
    if (ids.has(step.stepId)) throw new TypeError('duplicate job stepId: ' + step.stepId);
    ids.add(step.stepId);
  }
  if ('planHash' in data || 'schemaVersion' in data) throw new TypeError('planHash and schemaVersion are generated by NuBloxSQL');
  const envelope = { schemaVersion: 1, ...data };
  const planHash = crypto.createHash('sha256').update(JSON.stringify(canonical(envelope))).digest('hex');
  return deepFreeze({ ...envelope, planHash });
}

function createRun(plan, options = {}) {
  if (!plan || plan.schemaVersion !== SCHEMA_VERSION || typeof plan.planHash !== 'string' || !/^[0-9a-f]{64}$/.test(plan.planHash)) throw new TypeError('valid immutable job plan required');
  const runId = options.runId === undefined ? crypto.randomUUID() : nonEmpty(options.runId, 'runId');
  const queuedAt = options.now === undefined ? new Date().toISOString() : nonEmpty(options.now, 'now');
  if (!Number.isFinite(Date.parse(queuedAt))) throw new TypeError('now must be a valid date');
  return deepFreeze({ schemaVersion: 1, runId, planHash: plan.planHash, status: 'planned', version: 0, attempt: 0, createdAt: queuedAt, checkpoint: null });
}

function transition(run, nextStatus, options = {}) {
  if (!run || !TRANSITIONS[run.status] || !Number.isSafeInteger(run.version) || run.version < 0) throw new TypeError('valid job run required');
  nonEmpty(nextStatus, 'nextStatus');
  if (!TRANSITIONS[run.status].includes(nextStatus)) throw new Error('invalid job transition: ' + run.status + ' -> ' + nextStatus);
  const updated = { ...canonical(run), status: nextStatus, version: run.version + 1 };
  if (!LEASE_HOLDING.includes(nextStatus)) delete updated.lease;
  if (options.reason !== undefined) updated.reason = nonEmpty(options.reason, 'reason');
  if (options.now !== undefined) {
    if (!Number.isFinite(Date.parse(options.now))) throw new TypeError('now must be a valid date');
    updated.updatedAt = options.now;
  }
  return deepFreeze(updated);
}

function checkpoint(run, value, options = {}) {
  if (!run || run.status !== 'running' || !Number.isSafeInteger(run.version)) throw new Error('checkpoint requires a running job');
  const updated = { ...canonical(run), checkpoint: canonical(value), version: run.version + 1 };
  if (options.now !== undefined) {
    if (!Number.isFinite(Date.parse(options.now))) throw new TypeError('now must be a valid date');
    updated.updatedAt = options.now;
  }
  return deepFreeze(updated);
}

function createExecutorRegistry() {
  const executors = new Map();
  return Object.freeze({
    register(kind, executor) {
      nonEmpty(kind, 'job kind');
      if (!executor || typeof executor.execute !== 'function') throw new TypeError('executor must provide execute()');
      if (executors.has(kind)) throw new Error('executor already registered: ' + kind);
      executors.set(kind, executor);
    },
    resolve(kind) { return executors.get(kind) || null; },
    kinds() { return Object.freeze([...executors.keys()]); }
  });
}

function assertLease(run, options) {
  if (!run.lease || typeof run.lease !== 'object' ||
      !Number.isSafeInteger(run.lease.fence) || run.lease.fence < 1 ||
      options.workerId !== run.lease.workerId || options.fence !== run.lease.fence) {
    throw new Error('matching leased worker identity and fencing token required');
  }
}

function createKernel(store) {
  if (!store || ['savePlan', 'getPlan', 'createRun', 'getRun', 'commitTransition', 'leaseNextRun'].some(name => typeof store[name] !== 'function')) {
    throw new TypeError('durable JobStore adapter must implement savePlan, getPlan, createRun, getRun, commitTransition and leaseNextRun');
  }
  return Object.freeze({
    async submit(plan, options = {}) {
      if (!plan || plan.schemaVersion !== SCHEMA_VERSION ||
          createPlan(Object.fromEntries(Object.entries(plan).filter(([key]) => key !== 'planHash' && key !== 'schemaVersion'))).planHash !== plan.planHash) {
        throw new TypeError('job plan hash or schema version does not match content');
      }
      const run = createRun(plan, options);
      await store.savePlan(plan); // idempotent content-addressed write
      await store.createRun(run, { type: 'planned', runId: run.runId }); // atomic insertion + initial event
      return run;
    },
    async advance(runId, expectedVersion, nextStatus, options = {}) {
      nonEmpty(runId, 'runId');
      const current = await store.getRun(runId);
      if (!current || current.version !== expectedVersion) throw new Error('job run version conflict');
      if (nextStatus === 'leased' || (current.status === 'leased' && nextStatus === 'queued')) {
        throw new Error('leasing and lease recovery require atomic JobStore operations');
      }
      if (LEASE_HOLDING.includes(current.status)) assertLease(current, options);
      const next = transition(current, nextStatus, options);
      await store.commitTransition(runId, expectedVersion, next, { type: 'status', from: current.status, to: nextStatus, reason: options.reason || null });
      return next;
    },
    async checkpoint(runId, expectedVersion, value, options = {}) {
      nonEmpty(runId, 'runId');
      const current = await store.getRun(runId);
      if (!current || current.version !== expectedVersion) throw new Error('job run version conflict');
      assertLease(current, options);
      const next = checkpoint(current, value, options);
      await store.commitTransition(runId, expectedVersion, next, { type: 'checkpoint', runId });
      return next;
    },
    async leaseNext(workerId, now, expiresAt) {
      nonEmpty(workerId, 'workerId');
      if (!Number.isFinite(Date.parse(now)) || !Number.isFinite(Date.parse(expiresAt)) || Date.parse(expiresAt) <= Date.parse(now)) throw new TypeError('valid lease time range required');
      const leased = await store.leaseNextRun({ workerId, now, expiresAt }); // atomic claim + fencing is store-owned
      if (leased !== null && (!leased || leased.status !== 'leased' || !Number.isSafeInteger(leased.version) ||
          !leased.lease || leased.lease.workerId !== workerId || !Number.isSafeInteger(leased.lease.fence) ||
          leased.lease.fence < 1 || leased.lease.expiresAt !== expiresAt)) throw new Error('JobStore returned invalid lease');
      return leased;
    }
  });
}

module.exports = Object.freeze({ SCHEMA_VERSION: 1, TRANSITIONS, TERMINAL, LEASE_HOLDING, createPlan, createRun, transition, checkpoint, createExecutorRegistry, createKernel, safeCopy });
