'use strict';

var Tokenizer = require('./Tokenizer');
var Compiler = require('./Compiler');

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.keys(value).forEach(function (key) { deepFreeze(value[key]); });
  return Object.freeze(value);
}
function upper(value) { return String(value || '').toUpperCase(); }
function isWord(token, value) { return !!token && (token.type === 'identifier' || token.type === 'keyword') && upper(token.value) === value; }
function isAdvanced(ast) {
  return !!(ast && ast.type === 'CreateTableStatement' && Array.isArray(ast.columns) && ast.columns.some(function (column) { return !!(column.generated || column.identity); }));
}
function cloneBase(ast) {
  var result = {};
  Object.keys(ast).forEach(function (key) {
    if (key !== 'columns') result[key] = ast[key];
  });
  result.columns = ast.columns.map(function (column) {
    var copy = {};
    Object.keys(column).forEach(function (key) { if (key !== 'generated' && key !== 'identity') copy[key] = column[key]; });
    return copy;
  });
  return result;
}
function fakeSelect(expression) {
  return { type:'SelectStatement', with:null, distinct:false, columns:[expression], from:null, joins:[], where:null, groupBy:[], having:null, windows:[], orderBy:[], limit:null, offset:null };
}
function walk(value, visitor) {
  if (!value || typeof value !== 'object') return;
  visitor(value);
  if (Array.isArray(value)) { value.forEach(function (entry) { walk(entry, visitor); }); return; }
  Object.keys(value).forEach(function (key) { walk(value[key], visitor); });
}

function create(baseApi, normalizeDialect, rewriteApi) {
  function matchingParen(tokens, openIndex, end) {
    var depth = 0;
    for (var i = openIndex; i < end; i += 1) {
      if (tokens[i].type === 'punctuation' && tokens[i].value === '(') depth += 1;
      else if (tokens[i].type === 'punctuation' && tokens[i].value === ')') {
        depth -= 1;
        if (depth === 0) return i;
      }
    }
    throw new SyntaxError('Unclosed generated-column expression');
  }
  function definitionRanges(tokens, open, close) {
    var ranges = []; var depth = 0; var start = open + 1;
    for (var i = open + 1; i < close; i += 1) {
      if (tokens[i].type === 'punctuation' && tokens[i].value === '(') depth += 1;
      else if (tokens[i].type === 'punctuation' && tokens[i].value === ')') depth -= 1;
      else if (depth === 0 && tokens[i].type === 'punctuation' && tokens[i].value === ',') { ranges.push([start, i]); start = i + 1; }
    }
    ranges.push([start, close]);
    return ranges;
  }
  function parseExpression(source, text) {
    var parsed = baseApi.parseSql(source, 'SELECT ' + text);
    if (!parsed || parsed.type !== 'SelectStatement' || parsed.columns.length !== 1 || parsed.from) throw new SyntaxError('Generated column requires one scalar expression');
    var expression = parsed.columns[0];
    if (expression.type === 'AliasedExpression') throw new SyntaxError('Generated column expression cannot have an alias');
    walk(expression, function (node) {
      if (node.type === 'Parameter' || node.type === 'WindowExpression' || node.type === 'SubqueryExpression' || node.type === 'Wildcard') throw new RangeError('Generated column expression contains unsupported SQL');
    });
    return expression;
  }
  function inspect(sql, source) {
    if (!/^\s*CREATE\s+TABLE\b/i.test(sql)) return null;
    var tokens = Tokenizer.tokenize(sql, source);
    var open = -1;
    for (var i = 0; i < tokens.length; i += 1) { if (tokens[i].type === 'punctuation' && tokens[i].value === '(') { open = i; break; } }
    if (open < 0) return null;
    var close = matchingParen(tokens, open, tokens.length - 1);
    var replacements = []; var decorations = [];
    definitionRanges(tokens, open, close).forEach(function (range) {
      var start = range[0]; var end = range[1];
      if (!tokens[start] || tokens[start].type !== 'identifier') return;
      var columnName = String(tokens[start].value);
      var depth = 0; var generatedAt = -1;
      for (var j = start + 1; j < end; j += 1) {
        if (tokens[j].type === 'punctuation' && tokens[j].value === '(') depth += 1;
        else if (tokens[j].type === 'punctuation' && tokens[j].value === ')') depth -= 1;
        else if (depth === 0 && isWord(tokens[j], 'GENERATED')) { generatedAt = j; break; }
      }
      if (generatedAt < 0) return;
      var p = generatedAt + 1;
      var mode = null;
      if (isWord(tokens[p], 'ALWAYS')) { mode = 'always'; p += 1; }
      else if (isWord(tokens[p], 'BY') && isWord(tokens[p + 1], 'DEFAULT')) { mode = 'by-default'; p += 2; }
      if (!isWord(tokens[p], 'AS')) throw new SyntaxError('GENERATED column requires AS');
      p += 1;
      if (isWord(tokens[p], 'IDENTITY')) {
        if (!mode) throw new SyntaxError('Identity column requires GENERATED ALWAYS or GENERATED BY DEFAULT');
        if (source !== 'postgresql') throw new SyntaxError('Standard GENERATED ... AS IDENTITY is PostgreSQL source syntax in ddl-v6');
        p += 1;
        if (p !== end) throw new SyntaxError('ddl-v6 identity options beyond ALWAYS/BY DEFAULT are not yet supported');
        replacements.push({ start: tokens[generatedAt].start, end: tokens[p - 1].end, text: '' });
        decorations.push({ column: columnName, identity: { mode: mode } });
        return;
      }
      if (mode && mode !== 'always') throw new SyntaxError('Generated expression columns require GENERATED ALWAYS');
      if (!tokens[p] || tokens[p].type !== 'punctuation' || tokens[p].value !== '(') throw new SyntaxError('Generated column requires AS (expression)');
      var exprClose = matchingParen(tokens, p, end);
      var expressionText = sql.slice(tokens[p].end, tokens[exprClose].start);
      p = exprClose + 1;
      if (!isWord(tokens[p], 'STORED') && !isWord(tokens[p], 'VIRTUAL')) throw new SyntaxError('ddl-v6 requires explicit STORED or VIRTUAL generated-column mode');
      var storage = upper(tokens[p].value).toLowerCase(); p += 1;
      if (p !== end) throw new SyntaxError('Generated column must be the final ddl-v6 column clause');
      replacements.push({ start: tokens[generatedAt].start, end: tokens[p - 1].end, text: '' });
      decorations.push({ column: columnName, generated: { storage: storage, expression: parseExpression(source, expressionText) } });
    });
    if (!decorations.length) return null;
    var stripped = sql;
    replacements.sort(function (a, b) { return b.start - a.start; }).forEach(function (entry) { stripped = stripped.slice(0, entry.start) + entry.text + stripped.slice(entry.end); });
    return { sql: stripped, decorations: decorations };
  }
  function decorate(ast, decorations) {
    if (!ast || ast.type !== 'CreateTableStatement') throw new SyntaxError('Generated/identity columns require CREATE TABLE');
    var byName = Object.create(null);
    decorations.forEach(function (entry) { byName[String(entry.column).toLowerCase()] = entry; });
    var copy = {};
    Object.keys(ast).forEach(function (key) { copy[key] = ast[key]; });
    copy.columns = ast.columns.map(function (column) {
      var entry = byName[String(column.name.parts[0]).toLowerCase()];
      if (!entry) return column;
      var columnCopy = {};
      Object.keys(column).forEach(function (key) { columnCopy[key] = column[key]; });
      if (entry.generated) columnCopy.generated = entry.generated;
      if (entry.identity) columnCopy.identity = entry.identity;
      return columnCopy;
    });
    return copy;
  }
  function validate(ast) {
    if (!isAdvanced(ast)) throw new TypeError('NuBloxSQL ddl-v6 AST requires generated or identity columns');
    baseApi.analyzeAst(cloneBase(ast));
    ast.columns.forEach(function (column) {
      if (!column.generated && !column.identity) return;
      if (column.generated && column.identity) throw new RangeError('Column cannot be both generated and identity');
      if (column.default) throw new RangeError('Generated/identity column cannot also declare DEFAULT in ddl-v6');
      if (column.generated) {
        if (column.generated.storage !== 'stored' && column.generated.storage !== 'virtual') throw new RangeError('Generated column storage must be stored or virtual');
        baseApi.analyzeAst(fakeSelect(column.generated.expression));
      }
      if (column.identity && column.identity.mode !== 'always' && column.identity.mode !== 'by-default') throw new RangeError('Identity mode must be always or by-default');
    });
    return ast;
  }
  function parseSql(dialect, sql) {
    var source = normalizeDialect(dialect); var advanced = inspect(sql, source);
    if (!advanced) return baseApi.parseSql(source, sql);
    var ast = decorate(baseApi.parseSql(source, advanced.sql), advanced.decorations);
    validate(ast); return deepFreeze(ast);
  }
  function analyzeAst(ast) {
    if (!isAdvanced(ast)) return baseApi.analyzeAst(ast);
    validate(ast);
    var base = baseApi.analyzeAst(cloneBase(ast)); var set = Object.create(null);
    base.capabilities.forEach(function (path) { set[path] = true; });
    ast.columns.forEach(function (column) {
      if (column.generated) {
        set['integrity.generatedColumns'] = true;
        set[column.generated.storage === 'stored' ? 'integrity.generatedStored' : 'integrity.generatedVirtual'] = true;
        baseApi.analyzeAst(fakeSelect(column.generated.expression)).capabilities.forEach(function (path) { if (path !== 'statements.select') set[path] = true; });
      }
      if (column.identity) {
        set['integrity.identity'] = true;
        set[column.identity.mode === 'always' ? 'integrity.identityAlways' : 'integrity.identityByDefault'] = true;
      }
    });
    return deepFreeze({ statementType: ast.type, scope: 'ddl-v6', capabilities: Object.keys(set).sort() });
  }
  function quote(dialect, node) { return node.parts.map(function (part) { return Compiler.quoteIdentifier(dialect, part); }).join('.'); }
  function typeSql(node) { return node.name + (node.modifiers.length ? '(' + node.modifiers.join(', ') + ')' : ''); }
  function expressionSql(dialect, expression) {
    var compiled = baseApi.compileAst(dialect, fakeSelect(expression));
    if (compiled.targetToSource && compiled.targetToSource.length) throw new RangeError('Generated expressions cannot contain bind parameters');
    if (compiled.sql.slice(0, 7) !== 'SELECT ') throw new Error('Unexpected generated-expression compiler output');
    return compiled.sql.slice(7);
  }
  function compileAst(dialect, ast) {
    if (!isAdvanced(ast)) return baseApi.compileAst(dialect, ast);
    var target = normalizeDialect(dialect); validate(ast);
    if (ast.columns.some(function (column) { return column.identity; }) && target !== 'postgresql') throw new RangeError('SQL-standard identity in ddl-v6 is PostgreSQL-only; AUTO_INCREMENT/ROWID require explicit semantic lowering');
    var compiled = baseApi.compileAst(target, cloneBase(ast)); var sql = compiled.sql;
    ast.columns.forEach(function (column) {
      if (!column.generated && !column.identity) return;
      var prefix = quote(target, column.name) + ' ' + typeSql(column.dataType);
      var clause;
      if (column.identity) clause = column.identity.mode === 'always' ? 'GENERATED ALWAYS AS IDENTITY' : 'GENERATED BY DEFAULT AS IDENTITY';
      else clause = 'GENERATED ALWAYS AS (' + expressionSql(target, column.generated.expression) + ') ' + column.generated.storage.toUpperCase();
      if (sql.indexOf(prefix) < 0) throw new Error('Unable to locate ddl-v6 column in compiled CREATE TABLE');
      sql = sql.replace(prefix, prefix + ' ' + clause);
    });
    return deepFreeze({ dialect: target, sql: sql, targetToSource: compiled.targetToSource ? compiled.targetToSource.slice() : [] });
  }
  function qualificationEntry(report, path) {
    if (!report || !Array.isArray(report.entries)) return null;
    for (var i = 0; i < report.entries.length; i += 1) if (report.entries[i].path === path) return report.entries[i];
    return null;
  }
  function requirePostgresVirtualQualification(source, target, ast, options) {
    var hasVirtual = ast.columns.some(function (column) { return column.generated && column.generated.storage === 'virtual'; });
    if (!hasVirtual) return;
    if (source === 'postgresql') {
      var sourceEntry = qualificationEntry(options.sourceQualification, 'integrity.generatedVirtual');
      if (!sourceEntry || sourceEntry.resolved !== true || sourceEntry.supported !== true) throw new RangeError('PostgreSQL virtual generated columns require PostgreSQL 18+ source runtime qualification');
    }
    if (target === 'postgresql') {
      var targetEntry = qualificationEntry(options.targetQualification, 'integrity.generatedVirtual');
      if (!targetEntry || targetEntry.resolved !== true || targetEntry.supported !== true) throw new RangeError('PostgreSQL virtual generated columns require PostgreSQL 18+ target runtime qualification');
    }
  }
  function transpileSql(from, to, sql, options) {
    options = options || {};
    var source = normalizeDialect(from); var target = normalizeDialect(to); var ast = parseSql(source, sql);
    if (!isAdvanced(ast)) return baseApi.transpileSql(source, target, sql, options);
    requirePostgresVirtualQualification(source, target, ast, options);
    var analysis = analyzeAst(ast); var plan = rewriteApi.plan(source, target, analysis.capabilities, options);
    if (plan.blocked && options.allowBlocked !== true) {
      var blocked = plan.decisions.filter(function (entry) { return entry.action === 'reject'; }).map(function (entry) { return entry.path; });
      throw new RangeError('DDL ddl-v6 transpilation is blocked by unsupported target capabilities: ' + blocked.join(', '));
    }
    if (plan.requiresQualification && options.allowUnqualified !== true) {
      var unresolved = plan.decisions.filter(function (entry) { return entry.action === 'qualify'; }).map(function (entry) { return entry.path; });
      throw new RangeError('DDL ddl-v6 transpilation requires runtime qualification for: ' + unresolved.join(', '));
    }
    var transforms = plan.decisions.filter(function (entry) { return entry.action === 'emulate' || entry.action === 'rewrite'; });
    if (transforms.length) throw new RangeError('DDL ddl-v6 transpilation requires an explicit semantic transformation for: ' + transforms.map(function (entry) { return entry.path; }).join(', '));
    var compiled = compileAst(target, ast);
    var lossless = plan.decisions.every(function (entry) { return entry.lossless !== false && entry.action !== 'emulate'; });
    return deepFreeze({ from:source, to:target, scope:'ddl-v6', ast:ast, capabilities:analysis.capabilities, plan:plan, sql:compiled.sql, targetToSource:compiled.targetToSource, lossless:lossless, certified:plan.safeToProceed && lossless });
  }

  return Object.freeze({ parseSql:parseSql, analyzeAst:analyzeAst, compileAst:compileAst, transpileSql:transpileSql });
}

exports.create = create;
exports.isAdvancedAst = isAdvanced;
