'use strict';

module.exports = Object.freeze([
  Object.freeze([1, "ansi", "ISO/IEC", "Vendor-neutral SQL", "ISO/IEC Standard SQL", null, "standard", true]),
  Object.freeze([2, "postgresql", "PostgreSQL", "PostgreSQL", "PostgreSQL SQL", null, "primary-dialect", true]),
  Object.freeze([3, "cockroachdb", "Cockroach Labs", "CockroachDB", "CockroachDB SQL", "postgresql", "primary-dialect", true]),
  Object.freeze([4, "yugabytedb", "Yugabyte", "YugabyteDB", "Yugabyte SQL / PostgreSQL-compatible", "postgresql", "primary-dialect", true]),
  Object.freeze([5, "greenplum", "Broadcom", "VMware/Broadcom Greenplum", "Greenplum SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([6, "redshift", "Amazon", "Amazon Redshift", "Amazon Redshift SQL", "postgresql", "primary-dialect", true]),
  Object.freeze([7, "materialize", "Materialize", "Materialize", "Materialize SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([8, "risingwave", "RisingWave", "RisingWave", "RisingWave SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([9, "timescaledb", "Timescale", "TimescaleDB", "PostgreSQL + Timescale extensions", "postgresql", "dialect-profile", false]),
  Object.freeze([10, "citus", "Citus", "Citus", "PostgreSQL + Citus extensions", "postgresql", "dialect-profile", false]),
  Object.freeze([11, "alloydb", "Google", "Google AlloyDB", "PostgreSQL-compatible", "postgresql", "dialect-profile", false]),
  Object.freeze([12, "aurora-postgresql", "Amazon", "Amazon Aurora PostgreSQL", "PostgreSQL-compatible", "postgresql", "dialect-profile", false]),
  Object.freeze([13, "neon", "Neon", "Neon", "PostgreSQL", "postgresql", "dialect-profile", false]),
  Object.freeze([14, "supabase-postgresql", "Supabase", "Supabase PostgreSQL", "PostgreSQL", "postgresql", "dialect-profile", false]),
  Object.freeze([15, "mysql", "Oracle", "MySQL", "MySQL SQL", null, "primary-dialect", true]),
  Object.freeze([16, "mariadb", "MariaDB", "MariaDB", "MariaDB SQL", "mysql", "primary-dialect", true]),
  Object.freeze([17, "tidb", "PingCAP", "TiDB", "MySQL-compatible SQL", "mysql", "dialect-profile", false]),
  Object.freeze([18, "singlestore", "SingleStore", "SingleStore", "MySQL-derived SQL", "mysql", "dialect-profile", false]),
  Object.freeze([19, "aurora-mysql", "Amazon", "Amazon Aurora MySQL", "MySQL-compatible SQL", "mysql", "dialect-profile", false]),
  Object.freeze([20, "planetscale", "PlanetScale", "PlanetScale / Vitess", "MySQL/Vitess SQL", "mysql", "dialect-profile", false]),
  Object.freeze([21, "vitess", "Vitess", "Vitess", "MySQL-compatible / Vitess SQL", "mysql", "dialect-profile", false]),
  Object.freeze([22, "oceanbase-mysql", "OceanBase", "OceanBase", "OceanBase MySQL mode", "mysql", "compatibility-mode", false]),
  Object.freeze([23, "doris", "Apache", "Apache Doris", "MySQL-compatible analytical SQL", "mysql", "dialect-profile", false]),
  Object.freeze([24, "starrocks", "StarRocks", "StarRocks", "MySQL-compatible analytical SQL", "mysql", "dialect-profile", false]),
  Object.freeze([25, "sqlserver", "Microsoft", "Microsoft SQL Server", "Transact-SQL / T-SQL", null, "primary-dialect", true]),
  Object.freeze([26, "azure-sql", "Microsoft", "Azure SQL Database", "T-SQL", "sqlserver", "dialect-profile", false]),
  Object.freeze([27, "azure-managed-instance", "Microsoft", "Azure SQL Managed Instance", "T-SQL", "sqlserver", "dialect-profile", false]),
  Object.freeze([28, "synapse", "Microsoft", "Azure Synapse Analytics", "Synapse T-SQL", "sqlserver", "dialect-profile", false]),
  Object.freeze([29, "fabric", "Microsoft", "Fabric Warehouse / SQL endpoint", "Microsoft Fabric T-SQL", "sqlserver", "dialect-profile", false]),
  Object.freeze([30, "oracle", "Oracle", "Oracle Database", "Oracle SQL", null, "primary-dialect", true]),
  Object.freeze([31, "oracle-plsql", "Oracle", "Oracle Database procedural layer", "PL/SQL", "oracle", "procedural-layer", false]),
  Object.freeze([32, "oceanbase-oracle", "OceanBase", "OceanBase Oracle mode", "Oracle-compatible SQL", "oracle", "compatibility-mode", false]),
  Object.freeze([33, "db2-luw", "IBM", "Db2 for Linux/Unix/Windows", "IBM Db2 SQL", "db2", "dialect-profile", false]),
  Object.freeze([34, "db2-zos", "IBM", "IBM Db2 for z/OS", "Db2 SQL", "db2", "dialect-profile", false]),
  Object.freeze([35, "db2-i", "IBM", "IBM Db2 for i", "Db2 SQL", "db2", "dialect-profile", false]),
  Object.freeze([36, "sqlite", "SQLite", "SQLite", "SQLite SQL", null, "primary-dialect", true]),
  Object.freeze([37, "duckdb", "DuckDB", "DuckDB", "DuckDB SQL", null, "primary-dialect", true]),
  Object.freeze([38, "firebird", "Firebird", "Firebird", "Firebird SQL", null, "primary-dialect", true]),
  Object.freeze([39, "interbase", "Embarcadero", "Embarcadero InterBase", "InterBase SQL", null, "dialect", false]),
  Object.freeze([40, "informix", "IBM", "IBM Informix", "Informix SQL", null, "primary-dialect", true]),
  Object.freeze([41, "sybase-ase", "SAP", "SAP Adaptive Server Enterprise", "Transact-SQL / ASE SQL", null, "primary-dialect", true]),
  Object.freeze([42, "sql-anywhere", "SAP", "SAP SQL Anywhere", "SQL Anywhere SQL", null, "dialect", false]),
  Object.freeze([43, "sap-iq", "SAP", "SAP IQ", "SAP IQ SQL", null, "dialect", false]),
  Object.freeze([44, "hana", "SAP", "SAP HANA", "SAP HANA SQL", null, "primary-dialect", true]),
  Object.freeze([45, "maxdb", "SAP", "SAP MaxDB", "MaxDB SQL", null, "dialect", false]),
  Object.freeze([46, "teradata", "Teradata", "Teradata Vantage", "Teradata SQL", null, "primary-dialect", true]),
  Object.freeze([47, "snowflake", "Snowflake", "Snowflake", "Snowflake SQL", null, "primary-dialect", true]),
  Object.freeze([48, "bigquery", "Google", "Google BigQuery", "GoogleSQL", null, "primary-dialect", true]),
  Object.freeze([49, "bigquery-legacy", "Google", "Google BigQuery legacy mode", "BigQuery Legacy SQL", "bigquery", "legacy-mode", false]),
  Object.freeze([50, "spanner-google", "Google", "Google Cloud Spanner", "GoogleSQL for Spanner", null, "dialect", false]),
  Object.freeze([51, "spanner-postgresql", "Google", "Google Cloud Spanner", "PostgreSQL interface", "postgresql", "compatibility-interface", false]),
  Object.freeze([52, "spark", "Apache", "Apache Spark", "Spark SQL", null, "primary-dialect", true]),
  Object.freeze([53, "databricks", "Databricks", "Databricks SQL Warehouse", "Databricks SQL", null, "primary-dialect", true]),
  Object.freeze([54, "hive", "Apache", "Apache Hive", "HiveQL", null, "primary-dialect", true]),
  Object.freeze([55, "impala", "Apache", "Apache Impala", "Impala SQL", null, "dialect", false]),
  Object.freeze([56, "trino", "Trino", "Trino", "Trino SQL", null, "primary-dialect", true]),
  Object.freeze([57, "presto", "PrestoDB", "PrestoDB", "Presto SQL", null, "primary-dialect", true]),
  Object.freeze([58, "athena", "Amazon", "Amazon Athena", "Athena SQL / Trino-derived", "trino", "dialect-profile", false]),
  Object.freeze([59, "drill", "Apache", "Apache Drill", "Drill SQL", null, "dialect", false]),
  Object.freeze([60, "dremio", "Dremio", "Dremio", "Dremio SQL", null, "dialect", false]),
  Object.freeze([61, "clickhouse", "ClickHouse", "ClickHouse", "ClickHouse SQL", null, "primary-dialect", true]),
  Object.freeze([62, "vertica", "OpenText", "OpenText Vertica", "Vertica SQL", null, "dialect", false]),
  Object.freeze([63, "exasol", "Exasol", "Exasol", "Exasol SQL", null, "dialect", false]),
  Object.freeze([64, "monetdb", "MonetDB", "MonetDB", "MonetDB SQL", null, "dialect", false]),
  Object.freeze([65, "actian-ingres", "Actian", "Actian Ingres", "Ingres SQL", null, "dialect", false]),
  Object.freeze([66, "actian-vector", "Actian", "Actian Vector", "Vector SQL", "actian-ingres", "dialect-profile", false]),
  Object.freeze([67, "h2", "H2", "H2 Database", "H2 SQL", null, "dialect", false]),
  Object.freeze([68, "hsqldb", "HyperSQL", "HyperSQL", "HSQLDB SQL", null, "dialect", false]),
  Object.freeze([69, "derby", "Apache", "Apache Derby", "Derby SQL", null, "dialect", false]),
  Object.freeze([70, "openedge", "Progress", "Progress OpenEdge", "OpenEdge SQL", null, "dialect", false]),
  Object.freeze([71, "iris", "InterSystems", "InterSystems IRIS", "InterSystems SQL", null, "dialect", false]),
  Object.freeze([72, "cache", "InterSystems", "InterSystems Caché", "Caché SQL", null, "dialect", false]),
  Object.freeze([73, "virtuoso", "OpenLink", "OpenLink Virtuoso", "Virtuoso SQL/SPARQL", null, "dialect", false]),
  Object.freeze([74, "nuodb", "NuoDB", "NuoDB", "NuoDB SQL", null, "dialect", false]),
  Object.freeze([75, "voltdb", "VoltDB", "VoltDB", "VoltDB SQL", null, "dialect", false]),
  Object.freeze([76, "ydb", "YDB", "YDB", "YQL / SQL-like", null, "dialect", false]),
  Object.freeze([77, "questdb", "QuestDB", "QuestDB", "PostgreSQL-wire analytical SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([78, "times-ten", "Oracle", "Oracle TimesTen", "TimesTen SQL", "oracle", "dialect-profile", false]),
  Object.freeze([79, "solid", "IBM", "IBM solidDB", "solidDB SQL", null, "dialect", false]),
  Object.freeze([80, "mimer", "Mimer", "Mimer SQL", "Mimer SQL", null, "dialect", false]),
  Object.freeze([81, "frontbase", "FrontBase", "FrontBase", "FrontBase SQL", null, "dialect", false]),
  Object.freeze([82, "cubrid", "CUBRID", "CUBRID", "CUBRID SQL", null, "dialect", false]),
  Object.freeze([83, "altibase", "Altibase", "Altibase", "Altibase SQL", null, "dialect", false]),
  Object.freeze([84, "tibero", "TmaxSoft", "TmaxSoft Tibero", "Oracle-like SQL", "oracle", "dialect-profile", false]),
  Object.freeze([85, "dameng", "Dameng", "Dameng Database", "DM SQL", null, "dialect", false]),
  Object.freeze([86, "gaussdb", "Huawei", "Huawei GaussDB", "GaussDB SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([87, "opengauss", "openGauss", "openGauss", "PostgreSQL-derived SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([88, "kingbase", "Kingbase", "KingbaseES", "PostgreSQL-derived SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([89, "tdengine", "TDengine", "TDengine", "TDengine SQL", null, "dialect", false]),
  Object.freeze([90, "druid", "Apache", "Apache Druid", "Druid SQL", null, "dialect", false]),
  Object.freeze([91, "pinot", "Apache", "Apache Pinot", "Pinot SQL", null, "dialect", false]),
  Object.freeze([92, "kylin", "Apache", "Apache Kylin", "Kylin SQL", null, "dialect", false]),
  Object.freeze([93, "flink", "Apache", "Apache Flink", "Flink SQL", null, "dialect", false]),
  Object.freeze([94, "kafka-ksql", "Confluent", "Confluent ksqlDB", "ksqlDB SQL", null, "dialect", false]),
  Object.freeze([95, "esper", "EsperTech", "Esper", "EPL / SQL-like streaming language", null, "dialect", false]),
  Object.freeze([96, "heavydb", "HeavyAI", "HeavyDB", "HeavyDB SQL", null, "dialect", false]),
  Object.freeze([97, "yellowbrick", "Yellowbrick", "Yellowbrick", "PostgreSQL-derived SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([98, "netezza", "IBM", "IBM Netezza Performance Server", "Netezza SQL", null, "dialect", false]),
  Object.freeze([99, "hawq", "Apache", "Apache HAWQ", "PostgreSQL-derived SQL", "postgresql", "dialect-profile", false]),
  Object.freeze([100, "memsql-legacy", "SingleStore", "MemSQL → SingleStore", "MySQL-derived SQL", "singlestore", "legacy-product", false])
]);
