'use strict';

var TokenStream = require('./TokenStream');
var TOKENS = TokenStream.TOKENS;

var TYPES = Object.freeze({
  INT1:0x30, BIT:0x32, INT2:0x34, INT4:0x38, FLT4:0x3b, MONEY:0x3c,
  DATETIME:0x3d, FLT8:0x3e, MONEY4:0x7a, INT8:0x7f,
  INTN:0x26, BITN:0x68, FLOATN:0x6d,
  BIGVARBINARY:0xa5, BIGVARCHAR:0xa7, BIGBINARY:0xad, BIGCHAR:0xaf,
  NVARCHAR:0xe7, NCHAR:0xef
});

function need(buffer, offset, count, label) { if (offset + count > buffer.length) throw new RangeError('Incomplete SQL Server ' + label); }
function readColumnName(buffer, offset) { need(buffer,offset,1,'column-name length');var chars=buffer[offset++],bytes=chars*2;need(buffer,offset,bytes,'column name');return {value:buffer.toString('utf16le',offset,offset+bytes),offset:offset+bytes}; }
function parseTypeInfo(buffer, offset) {
  need(buffer,offset,1,'TYPE_INFO');var type=buffer[offset++],info={type:type,maxLength:null,collation:null};
  if([TYPES.INT1,TYPES.BIT,TYPES.INT2,TYPES.INT4,TYPES.INT8,TYPES.FLT4,TYPES.FLT8,TYPES.MONEY,TYPES.MONEY4,TYPES.DATETIME].indexOf(type)!==-1)return {info:Object.freeze(info),offset:offset};
  if([TYPES.INTN,TYPES.BITN,TYPES.FLOATN].indexOf(type)!==-1){need(buffer,offset,1,'variable numeric TYPE_INFO length');info.maxLength=buffer[offset++];return {info:Object.freeze(info),offset:offset};}
  if([TYPES.BIGVARCHAR,TYPES.BIGCHAR,TYPES.NVARCHAR,TYPES.NCHAR].indexOf(type)!==-1){need(buffer,offset,7,'character TYPE_INFO');info.maxLength=buffer.readUInt16LE(offset);offset+=2;info.collation=Buffer.from(buffer.subarray(offset,offset+5));offset+=5;return {info:Object.freeze(info),offset:offset};}
  if(type===TYPES.BIGVARBINARY||type===TYPES.BIGBINARY){need(buffer,offset,2,'binary TYPE_INFO');info.maxLength=buffer.readUInt16LE(offset);offset+=2;return {info:Object.freeze(info),offset:offset};}
  throw new RangeError('Unsupported SQL Server result type 0x'+type.toString(16).padStart(2,'0'));
}
function parseColumnMetadata(buffer,offset){need(buffer,offset,3,'COLMETADATA header');if(buffer[offset]!==TOKENS.COLMETADATA)throw new RangeError('Expected SQL Server COLMETADATA token');var count=buffer.readUInt16LE(offset+1),cursor=offset+3,columns=[];if(count===0xffff)return {columns:Object.freeze([]),offset:cursor};for(var i=0;i<count;i++){need(buffer,cursor,6,'column metadata');var userType=buffer.readUInt32LE(cursor);cursor+=4;var flags=buffer.readUInt16LE(cursor);cursor+=2;var parsedType=parseTypeInfo(buffer,cursor);cursor=parsedType.offset;var name=readColumnName(buffer,cursor);cursor=name.offset;columns.push(Object.freeze({name:name.value,userType:userType,flags:flags,nullable:(flags&1)!==0,type:parsedType.info.type,maxLength:parsedType.info.maxLength,collation:parsedType.info.collation}));}return {columns:Object.freeze(columns),offset:cursor};}
function fixedWidth(type){if(type===TYPES.INT1||type===TYPES.BIT)return 1;if(type===TYPES.INT2)return 2;if(type===TYPES.INT4||type===TYPES.FLT4||type===TYPES.MONEY4)return 4;if(type===TYPES.INT8||type===TYPES.FLT8||type===TYPES.MONEY||type===TYPES.DATETIME)return 8;return null;}
function decodeFixed(buffer,offset,type,width){need(buffer,offset,width,'row value');var value;if(type===TYPES.INT1)value=buffer[offset];else if(type===TYPES.BIT)value=buffer[offset]!==0;else if(type===TYPES.INT2)value=buffer.readInt16LE(offset);else if(type===TYPES.INT4)value=buffer.readInt32LE(offset);else if(type===TYPES.INT8)value=buffer.readBigInt64LE(offset);else if(type===TYPES.FLT4)value=buffer.readFloatLE(offset);else if(type===TYPES.FLT8)value=buffer.readDoubleLE(offset);else throw new RangeError('SQL Server fixed result type is not decoded yet: 0x'+type.toString(16));return {value:value,offset:offset+width};}
function decodeVariableNumeric(buffer,offset,column){need(buffer,offset,1,'variable numeric length');var length=buffer[offset++];if(length===0)return {value:null,offset:offset};need(buffer,offset,length,'variable numeric value');var value;if(column.type===TYPES.BITN){if(length!==1)throw new RangeError('Invalid SQL Server BITN length '+length);value=buffer[offset]!==0;}else if(column.type===TYPES.INTN){if(length===1)value=buffer[offset];else if(length===2)value=buffer.readInt16LE(offset);else if(length===4)value=buffer.readInt32LE(offset);else if(length===8)value=buffer.readBigInt64LE(offset);else throw new RangeError('Invalid SQL Server INTN length '+length);}else if(column.type===TYPES.FLOATN){if(length===4)value=buffer.readFloatLE(offset);else if(length===8)value=buffer.readDoubleLE(offset);else throw new RangeError('Invalid SQL Server FLOATN length '+length);}return {value:value,offset:offset+length};}
function decodeCharacterOrBinary(buffer,offset,column){need(buffer,offset,2,'character/binary length');var length=buffer.readUInt16LE(offset);offset+=2;if(length===0xffff)return {value:null,offset:offset};if(column.maxLength===0xffff)throw new RangeError('SQL Server PLP/MAX values are not supported yet');need(buffer,offset,length,'character/binary value');var end=offset+length,value;if(column.type===TYPES.NVARCHAR||column.type===TYPES.NCHAR)value=buffer.toString('utf16le',offset,end);else if(column.type===TYPES.BIGVARCHAR||column.type===TYPES.BIGCHAR)value=buffer.toString('utf8',offset,end);else value=Buffer.from(buffer.subarray(offset,end));return {value:value,offset:end};}
function decodeColumn(buffer,offset,column){var width=fixedWidth(column.type);if(width!==null)return decodeFixed(buffer,offset,column.type,width);if(column.type===TYPES.INTN||column.type===TYPES.BITN||column.type===TYPES.FLOATN)return decodeVariableNumeric(buffer,offset,column);if([TYPES.BIGVARCHAR,TYPES.BIGCHAR,TYPES.NVARCHAR,TYPES.NCHAR,TYPES.BIGVARBINARY,TYPES.BIGBINARY].indexOf(column.type)!==-1)return decodeCharacterOrBinary(buffer,offset,column);throw new RangeError('Unsupported SQL Server row type 0x'+column.type.toString(16));}
function parseRow(buffer,offset,columns,nullCompressed){var expected=nullCompressed?TOKENS.NBCROW:TOKENS.ROW;if(buffer[offset]!==expected)throw new RangeError('Expected SQL Server '+(nullCompressed?'NBCROW':'ROW')+' token');var cursor=offset+1,bitmap=null;if(nullCompressed){var bytes=Math.ceil(columns.length/8);need(buffer,cursor,bytes,'NBCROW null bitmap');bitmap=buffer.subarray(cursor,cursor+bytes);cursor+=bytes;}var row={};for(var i=0;i<columns.length;i++){var isNull=bitmap&&(bitmap[Math.floor(i/8)]&(1<<(i%8)))!==0;if(isNull)row[columns[i].name]=null;else{var decoded=decodeColumn(buffer,cursor,columns[i]);cursor=decoded.offset;row[columns[i].name]=decoded.value;}}return {row:Object.freeze(row),offset:cursor};}
function parse(payload){var buffer=Buffer.from(payload),cursor=0,columns=Object.freeze([]),rows=[],errors=[],info=[],done=null,returnStatus=null;while(cursor<buffer.length){var token=buffer[cursor],parsed;if(token===TOKENS.COLMETADATA){parsed=parseColumnMetadata(buffer,cursor);columns=parsed.columns;cursor=parsed.offset;continue;}if(token===TOKENS.ROW||token===TOKENS.NBCROW){parsed=parseRow(buffer,cursor,columns,token===TOKENS.NBCROW);rows.push(parsed.row);cursor=parsed.offset;continue;}if(token===TOKENS.ERROR||token===TOKENS.INFO){parsed=TokenStream.parseMessage(buffer,cursor,token===TOKENS.ERROR?'error':'info');if(parsed.type==='error')errors.push(parsed);else info.push(parsed);cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.ENVCHANGE){parsed=TokenStream.parseEnvChange(buffer,cursor);cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.RETURNSTATUS){parsed=TokenStream.parseReturnStatus(buffer,cursor);returnStatus=parsed.value;cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.DONE||token===TOKENS.DONEPROC||token===TOKENS.DONEINPROC){parsed=TokenStream.parseDone(buffer,cursor);done=parsed;cursor+=parsed.bytesConsumed;continue;}throw new RangeError('Unsupported SQL Server result token 0x'+token.toString(16).padStart(2,'0'));}return Object.freeze({columns:columns,rows:Object.freeze(rows),errors:Object.freeze(errors),info:Object.freeze(info),rowCount:done&&done.hasRowCount?done.rowCount:BigInt(rows.length),done:done,returnStatus:returnStatus,success:errors.length===0&&(!done||!done.error)});}

exports.TOKENS=TOKENS;
exports.TYPES=TYPES;
exports.parseTypeInfo=parseTypeInfo;
exports.parseColumnMetadata=parseColumnMetadata;
exports.parseRow=parseRow;
exports.parse=parse;
