'use strict';

var TokenStream=require('./TokenStream');
var Plp=require('./Plp');
var TOKENS=TokenStream.TOKENS;

var TYPES=Object.freeze({
  GUID:0x24,
  INTN:0x26,DATE:0x28,TIME:0x29,DATETIME2:0x2a,DATETIMEOFFSET:0x2b,
  INT1:0x30,BIT:0x32,INT2:0x34,DECIMAL:0x37,INT4:0x38,DATETIME4:0x3a,
  FLT4:0x3b,MONEY:0x3c,DATETIME:0x3d,FLT8:0x3e,NUMERIC:0x3f,
  BITN:0x68,DECIMALN:0x6a,NUMERICN:0x6c,FLOATN:0x6d,MONEYN:0x6e,
  MONEY4:0x7a,INT8:0x7f,
  BIGVARBINARY:0xa5,BIGVARCHAR:0xa7,BIGBINARY:0xad,BIGCHAR:0xaf,
  NVARCHAR:0xe7,NCHAR:0xef
});

var BASE_DATE_MS=-62135596800000;
var DAY_MS=86400000;

function need(buffer,offset,count,label){if(offset+count>buffer.length)throw new RangeError('Incomplete SQL Server '+label);}
function pad(value,length){return String(value).padStart(length,'0');}
function pow10(scale){var result=1n;for(var i=0;i<scale;i++)result*=10n;return result;}
function readUnsignedBigIntLE(buffer,offset,length){need(buffer,offset,length,'unsigned integer');var value=0n;for(var i=length-1;i>=0;i--)value=(value<<8n)|BigInt(buffer[offset+i]);return value;}
function readMoney64(buffer,offset){need(buffer,offset,8,'MONEY value');var high=BigInt(buffer.readInt32LE(offset));var low=BigInt(buffer.readUInt32LE(offset+4));return(high<<32n)+low;}
function formatScaledInteger(value,scale){var negative=value<0n,magnitude=negative?-value:value,digits=magnitude.toString();if(scale>0){if(digits.length<=scale)digits='0'.repeat(scale-digits.length+1)+digits;digits=digits.slice(0,-scale)+'.'+digits.slice(-scale);}return(negative?'-':'')+digits;}
function formatDate(days){var date=new Date(BASE_DATE_MS+(days*DAY_MS));if(!Number.isFinite(date.getTime()))throw new RangeError('SQL Server date is outside JavaScript calendar formatting range');return pad(date.getUTCFullYear(),4)+'-'+pad(date.getUTCMonth()+1,2)+'-'+pad(date.getUTCDate(),2);}
function timeLength(scale){return scale<=2?3:(scale<=4?4:5);}
function formatTime(units,scale){var divisor=pow10(scale),whole=units/divisor,fraction=units%divisor,hours=whole/3600n,minutes=(whole%3600n)/60n,seconds=whole%60n,result=pad(hours.toString(),2)+':'+pad(minutes.toString(),2)+':'+pad(seconds.toString(),2);if(scale>0)result+='.'+fraction.toString().padStart(scale,'0');return result;}
function readColumnName(buffer,offset){need(buffer,offset,1,'column-name length');var chars=buffer[offset++],bytes=chars*2;need(buffer,offset,bytes,'column name');return{value:buffer.toString('utf16le',offset,offset+bytes),offset:offset+bytes};}
function parseTypeInfo(buffer,offset){
  need(buffer,offset,1,'TYPE_INFO');
  var type=buffer[offset++],info={type:type,maxLength:null,collation:null,precision:null,scale:null};
  if([TYPES.INT1,TYPES.BIT,TYPES.INT2,TYPES.INT4,TYPES.INT8,TYPES.FLT4,TYPES.FLT8,TYPES.MONEY,TYPES.MONEY4,TYPES.DATETIME,TYPES.DATETIME4].indexOf(type)!==-1)return{info:Object.freeze(info),offset:offset};
  if(type===TYPES.DATE)return{info:Object.freeze(info),offset:offset};
  if(type===TYPES.GUID){need(buffer,offset,1,'GUID TYPE_INFO length');info.maxLength=buffer[offset++];if(info.maxLength!==16)throw new RangeError('Invalid SQL Server GUID TYPE_INFO length '+info.maxLength);return{info:Object.freeze(info),offset:offset};}
  if([TYPES.TIME,TYPES.DATETIME2,TYPES.DATETIMEOFFSET].indexOf(type)!==-1){need(buffer,offset,1,'temporal TYPE_INFO scale');info.scale=buffer[offset++];if(info.scale>7)throw new RangeError('Invalid SQL Server temporal scale '+info.scale);return{info:Object.freeze(info),offset:offset};}
  if([TYPES.INTN,TYPES.BITN,TYPES.FLOATN,TYPES.MONEYN].indexOf(type)!==-1){need(buffer,offset,1,'variable numeric TYPE_INFO length');info.maxLength=buffer[offset++];return{info:Object.freeze(info),offset:offset};}
  if([TYPES.DECIMAL,TYPES.NUMERIC,TYPES.DECIMALN,TYPES.NUMERICN].indexOf(type)!==-1){if(type===TYPES.DECIMALN||type===TYPES.NUMERICN){need(buffer,offset,1,'decimal TYPE_INFO length');info.maxLength=buffer[offset++];}need(buffer,offset,2,'decimal TYPE_INFO precision and scale');info.precision=buffer[offset++];info.scale=buffer[offset++];if(info.precision<1||info.precision>38||info.scale>info.precision)throw new RangeError('Invalid SQL Server decimal precision/scale');return{info:Object.freeze(info),offset:offset};}
  if([TYPES.BIGVARCHAR,TYPES.BIGCHAR,TYPES.NVARCHAR,TYPES.NCHAR].indexOf(type)!==-1){need(buffer,offset,7,'character TYPE_INFO');info.maxLength=buffer.readUInt16LE(offset);offset+=2;info.collation=Buffer.from(buffer.subarray(offset,offset+5));offset+=5;return{info:Object.freeze(info),offset:offset};}
  if(type===TYPES.BIGVARBINARY||type===TYPES.BIGBINARY){need(buffer,offset,2,'binary TYPE_INFO');info.maxLength=buffer.readUInt16LE(offset);offset+=2;return{info:Object.freeze(info),offset:offset};}
  throw new RangeError('Unsupported SQL Server result type 0x'+type.toString(16).padStart(2,'0'));
}
function parseColumnMetadata(buffer,offset){need(buffer,offset,3,'COLMETADATA header');if(buffer[offset]!==TOKENS.COLMETADATA)throw new RangeError('Expected SQL Server COLMETADATA token');var count=buffer.readUInt16LE(offset+1),cursor=offset+3,columns=[];if(count===0xffff)return{columns:Object.freeze([]),offset:cursor};for(var i=0;i<count;i++){need(buffer,cursor,6,'column metadata');var userType=buffer.readUInt32LE(cursor);cursor+=4;var flags=buffer.readUInt16LE(cursor);cursor+=2;var parsedType=parseTypeInfo(buffer,cursor);cursor=parsedType.offset;var name=readColumnName(buffer,cursor);cursor=name.offset;columns.push(Object.freeze({name:name.value,userType:userType,flags:flags,nullable:(flags&1)!==0,type:parsedType.info.type,maxLength:parsedType.info.maxLength,collation:parsedType.info.collation,precision:parsedType.info.precision,scale:parsedType.info.scale}));}return{columns:Object.freeze(columns),offset:cursor};}
function fixedWidth(type){if(type===TYPES.INT1||type===TYPES.BIT)return 1;if(type===TYPES.INT2)return 2;if(type===TYPES.INT4||type===TYPES.FLT4||type===TYPES.MONEY4||type===TYPES.DATETIME4)return 4;if(type===TYPES.INT8||type===TYPES.FLT8||type===TYPES.MONEY||type===TYPES.DATETIME)return 8;return null;}
function decodeMoneyInteger(value){return formatScaledInteger(value,4);}
function decodeLegacyDateTime(buffer,offset,type){if(type===TYPES.DATETIME4){var days=buffer.readUInt16LE(offset),minutes=buffer.readUInt16LE(offset+2),date=new Date(Date.UTC(1900,0,1)+(days*DAY_MS)+(minutes*60000));return pad(date.getUTCFullYear(),4)+'-'+pad(date.getUTCMonth()+1,2)+'-'+pad(date.getUTCDate(),2)+'T'+pad(date.getUTCHours(),2)+':'+pad(date.getUTCMinutes(),2)+':00';}var dayCount=buffer.readInt32LE(offset),ticks=buffer.readUInt32LE(offset+4),totalMillis=Math.round(ticks*1000/300),value=new Date(Date.UTC(1900,0,1)+(dayCount*DAY_MS)+totalMillis);return pad(value.getUTCFullYear(),4)+'-'+pad(value.getUTCMonth()+1,2)+'-'+pad(value.getUTCDate(),2)+'T'+pad(value.getUTCHours(),2)+':'+pad(value.getUTCMinutes(),2)+':'+pad(value.getUTCSeconds(),2)+'.'+pad(value.getUTCMilliseconds(),3);}
function decodeFixed(buffer,offset,type,width){need(buffer,offset,width,'row value');var value;if(type===TYPES.INT1)value=buffer[offset];else if(type===TYPES.BIT)value=buffer[offset]!==0;else if(type===TYPES.INT2)value=buffer.readInt16LE(offset);else if(type===TYPES.INT4)value=buffer.readInt32LE(offset);else if(type===TYPES.INT8)value=buffer.readBigInt64LE(offset);else if(type===TYPES.FLT4)value=buffer.readFloatLE(offset);else if(type===TYPES.FLT8)value=buffer.readDoubleLE(offset);else if(type===TYPES.MONEY)value=decodeMoneyInteger(readMoney64(buffer,offset));else if(type===TYPES.MONEY4)value=decodeMoneyInteger(BigInt(buffer.readInt32LE(offset)));else if(type===TYPES.DATETIME||type===TYPES.DATETIME4)value=decodeLegacyDateTime(buffer,offset,type);else throw new RangeError('SQL Server fixed result type is not decoded yet: 0x'+type.toString(16));return{value:value,offset:offset+width};}
function decodeVariableNumeric(buffer,offset,column){need(buffer,offset,1,'variable numeric length');var length=buffer[offset++];if(length===0)return{value:null,offset:offset};need(buffer,offset,length,'variable numeric value');var value;if(column.type===TYPES.BITN){if(length!==1)throw new RangeError('Invalid SQL Server BITN length '+length);value=buffer[offset]!==0;}else if(column.type===TYPES.INTN){if(length===1)value=buffer[offset];else if(length===2)value=buffer.readInt16LE(offset);else if(length===4)value=buffer.readInt32LE(offset);else if(length===8)value=buffer.readBigInt64LE(offset);else throw new RangeError('Invalid SQL Server INTN length '+length);}else if(column.type===TYPES.FLOATN){if(length===4)value=buffer.readFloatLE(offset);else if(length===8)value=buffer.readDoubleLE(offset);else throw new RangeError('Invalid SQL Server FLOATN length '+length);}else if(column.type===TYPES.MONEYN){if(length===4)value=decodeMoneyInteger(BigInt(buffer.readInt32LE(offset)));else if(length===8)value=decodeMoneyInteger(readMoney64(buffer,offset));else throw new RangeError('Invalid SQL Server MONEYN length '+length);}return{value:value,offset:offset+length};}
function decodeDecimal(buffer,offset,column,fixed){var length;if(fixed)length=column.precision<=9?5:(column.precision<=19?9:(column.precision<=28?13:17));else{need(buffer,offset,1,'decimal length');length=buffer[offset++];if(length===0)return{value:null,offset:offset};}need(buffer,offset,length,'decimal value');if(length<2)throw new RangeError('Invalid SQL Server decimal value length '+length);var sign=buffer[offset++];if(sign!==0&&sign!==1)throw new RangeError('Invalid SQL Server decimal sign '+sign);var magnitude=readUnsignedBigIntLE(buffer,offset,length-1);offset+=length-1;return{value:formatScaledInteger(sign===0?-magnitude:magnitude,column.scale||0),offset:offset};}
function decodeGuid(buffer,offset){need(buffer,offset,1,'GUID length');var length=buffer[offset++];if(length===0)return{value:null,offset:offset};if(length!==16)throw new RangeError('Invalid SQL Server GUID length '+length);need(buffer,offset,16,'GUID value');var a=buffer.readUInt32LE(offset).toString(16).padStart(8,'0'),b=buffer.readUInt16LE(offset+4).toString(16).padStart(4,'0'),c=buffer.readUInt16LE(offset+6).toString(16).padStart(4,'0'),d=buffer.subarray(offset+8,offset+10).toString('hex'),e=buffer.subarray(offset+10,offset+16).toString('hex');return{value:a+'-'+b+'-'+c+'-'+d+'-'+e,offset:offset+16};}
function decodeTemporal(buffer,offset,column){need(buffer,offset,1,'temporal length');var length=buffer[offset++];if(length===0)return{value:null,offset:offset};var type=column.type,scale=column.scale===null?0:column.scale,tlen=timeLength(scale),expected=type===TYPES.DATE?3:(type===TYPES.TIME?tlen:(type===TYPES.DATETIME2?tlen+3:tlen+5));if(length!==expected)throw new RangeError('Invalid SQL Server temporal length '+length+' for type 0x'+type.toString(16));need(buffer,offset,length,'temporal value');if(type===TYPES.DATE){var dateDays=Number(readUnsignedBigIntLE(buffer,offset,3));return{value:formatDate(dateDays),offset:offset+3};}var units=readUnsignedBigIntLE(buffer,offset,tlen),cursor=offset+tlen;if(type===TYPES.TIME)return{value:formatTime(units,scale),offset:cursor};var days=Number(readUnsignedBigIntLE(buffer,cursor,3));cursor+=3;if(type===TYPES.DATETIME2)return{value:formatDate(days)+'T'+formatTime(units,scale),offset:cursor};var zone=buffer.readInt16LE(cursor);cursor+=2;var perSecond=pow10(scale),perDay=86400n*perSecond,localTotal=BigInt(days)*perDay+units+BigInt(zone)*60n*perSecond,localDays=localTotal/perDay,localUnits=localTotal%perDay;if(localUnits<0n){localUnits+=perDay;localDays-=1n;}var sign=zone<0?'-':'+';var abs=Math.abs(zone);return{value:formatDate(Number(localDays))+'T'+formatTime(localUnits,scale)+sign+pad(Math.floor(abs/60),2)+':'+pad(abs%60,2),offset:cursor};}
function decodePlpValue(buffer,offset,column){var parsed=Plp.read(buffer,offset);if(parsed.value===null)return{value:null,offset:parsed.offset};var raw=parsed.value,value;if(column.type===TYPES.NVARCHAR||column.type===TYPES.NCHAR){if((raw.length&1)!==0)throw new RangeError('SQL Server NVARCHAR(MAX) PLP value has odd byte length');value=raw.toString('utf16le');}else if(column.type===TYPES.BIGVARCHAR||column.type===TYPES.BIGCHAR)value=raw.toString('utf8');else value=Buffer.from(raw);return{value:value,offset:parsed.offset};}
function decodeCharacterOrBinary(buffer,offset,column){if(column.maxLength===0xffff)return decodePlpValue(buffer,offset,column);need(buffer,offset,2,'character/binary length');var length=buffer.readUInt16LE(offset);offset+=2;if(length===0xffff)return{value:null,offset:offset};need(buffer,offset,length,'character/binary value');var end=offset+length,value;if(column.type===TYPES.NVARCHAR||column.type===TYPES.NCHAR)value=buffer.toString('utf16le',offset,end);else if(column.type===TYPES.BIGVARCHAR||column.type===TYPES.BIGCHAR)value=buffer.toString('utf8',offset,end);else value=Buffer.from(buffer.subarray(offset,end));return{value:value,offset:end};}
function decodeColumn(buffer,offset,column){var width=fixedWidth(column.type);if(width!==null)return decodeFixed(buffer,offset,column.type,width);if(column.type===TYPES.INTN||column.type===TYPES.BITN||column.type===TYPES.FLOATN||column.type===TYPES.MONEYN)return decodeVariableNumeric(buffer,offset,column);if(column.type===TYPES.DECIMAL||column.type===TYPES.NUMERIC)return decodeDecimal(buffer,offset,column,true);if(column.type===TYPES.DECIMALN||column.type===TYPES.NUMERICN)return decodeDecimal(buffer,offset,column,false);if(column.type===TYPES.GUID)return decodeGuid(buffer,offset);if(column.type===TYPES.DATE||column.type===TYPES.TIME||column.type===TYPES.DATETIME2||column.type===TYPES.DATETIMEOFFSET)return decodeTemporal(buffer,offset,column);if([TYPES.BIGVARCHAR,TYPES.BIGCHAR,TYPES.NVARCHAR,TYPES.NCHAR,TYPES.BIGVARBINARY,TYPES.BIGBINARY].indexOf(column.type)!==-1)return decodeCharacterOrBinary(buffer,offset,column);throw new RangeError('Unsupported SQL Server row type 0x'+column.type.toString(16));}
function parseRow(buffer,offset,columns,nullCompressed){var expected=nullCompressed?TOKENS.NBCROW:TOKENS.ROW;if(buffer[offset]!==expected)throw new RangeError('Expected SQL Server '+(nullCompressed?'NBCROW':'ROW')+' token');var cursor=offset+1,bitmap=null;if(nullCompressed){var bytes=Math.ceil(columns.length/8);need(buffer,cursor,bytes,'NBCROW null bitmap');bitmap=buffer.subarray(cursor,cursor+bytes);cursor+=bytes;}var row={};for(var i=0;i<columns.length;i++){var isNull=bitmap&&(bitmap[Math.floor(i/8)]&(1<<(i%8)))!==0;if(isNull)row[columns[i].name]=null;else{var decoded=decodeColumn(buffer,cursor,columns[i]);cursor=decoded.offset;row[columns[i].name]=decoded.value;}}return{row:Object.freeze(row),offset:cursor};}
function parse(payload){var buffer=Buffer.from(payload),cursor=0,columns=Object.freeze([]),rows=[],errors=[],info=[],envChanges=[],order=Object.freeze([]),done=null,returnStatus=null;while(cursor<buffer.length){var token=buffer[cursor],parsed;if(token===TOKENS.COLMETADATA){parsed=parseColumnMetadata(buffer,cursor);columns=parsed.columns;cursor=parsed.offset;continue;}if(token===TOKENS.ROW||token===TOKENS.NBCROW){parsed=parseRow(buffer,cursor,columns,token===TOKENS.NBCROW);rows.push(parsed.row);cursor=parsed.offset;continue;}if(token===TOKENS.ORDER){parsed=TokenStream.parseOrder(buffer,cursor);order=parsed.columns;cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.ERROR||token===TOKENS.INFO){parsed=TokenStream.parseMessage(buffer,cursor,token===TOKENS.ERROR?'error':'info');if(parsed.type==='error')errors.push(parsed);else info.push(parsed);cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.ENVCHANGE){parsed=TokenStream.parseEnvChange(buffer,cursor);envChanges.push(parsed);cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.RETURNSTATUS){parsed=TokenStream.parseReturnStatus(buffer,cursor);returnStatus=parsed.value;cursor+=parsed.bytesConsumed;continue;}if(token===TOKENS.DONE||token===TOKENS.DONEPROC||token===TOKENS.DONEINPROC){parsed=TokenStream.parseDone(buffer,cursor);done=parsed;cursor+=parsed.bytesConsumed;continue;}throw new RangeError('Unsupported SQL Server result token 0x'+token.toString(16).padStart(2,'0'));}return Object.freeze({columns:columns,rows:Object.freeze(rows),errors:Object.freeze(errors),info:Object.freeze(info),envChanges:Object.freeze(envChanges),order:order,rowCount:done&&done.hasRowCount?done.rowCount:BigInt(rows.length),done:done,returnStatus:returnStatus,success:errors.length===0&&(!done||!done.error)});}

exports.TOKENS=TOKENS;
exports.TYPES=TYPES;
exports.formatScaledInteger=formatScaledInteger;
exports.formatDate=formatDate;
exports.formatTime=formatTime;
exports.parseTypeInfo=parseTypeInfo;
exports.parseColumnMetadata=parseColumnMetadata;
exports.parseRow=parseRow;
exports.parse=parse;
