'use strict';

exports.PROTOCOL_VERSION_3_0 = 196608;
exports.PROTOCOL_VERSION_3_2 = 196610;
exports.SSL_REQUEST_CODE = 80877103;
exports.CANCEL_REQUEST_CODE = 80877102;

exports.AUTHENTICATION = Object.freeze({
  OK: 0,
  KERBEROS_V5: 2,
  CLEARTEXT_PASSWORD: 3,
  MD5_PASSWORD: 5,
  SCM_CREDENTIAL: 6,
  GSS: 7,
  GSS_CONTINUE: 8,
  SSPI: 9,
  SASL: 10,
  SASL_CONTINUE: 11,
  SASL_FINAL: 12
});

exports.BACKEND_MESSAGE_TYPES = Object.freeze({
  AUTHENTICATION: 'R',
  BACKEND_KEY_DATA: 'K',
  ERROR_RESPONSE: 'E',
  NOTICE_RESPONSE: 'N',
  PARAMETER_STATUS: 'S',
  READY_FOR_QUERY: 'Z',
  COPY_IN_RESPONSE: 'G',
  COPY_OUT_RESPONSE: 'H',
  COPY_BOTH_RESPONSE: 'W',
  COPY_DATA: 'd',
  COPY_DONE: 'c'
});
